### ISSUE TITLE
网站底部的推特帐号不存在

### ISSUE THREAD

**Issue by CyrusYip** [rbind/liechi#4]
<https://twitter.com/liechizhang>

![Screenshot_20210117_222638](https://user-images.githubusercontent.com/60951091/104846042-778e5780-5913-11eb-9d3c-7b662a9fa1b1.png)

**Comment by liechi** [comment]
谢谢，正确的应该是这个：https://twitter.com/ZhangLiechi
不过这个账号是空的，虽然已经注册了很多年了。
我在社交网络上几乎没有任何活动，所以下边那排联系方式没有什么用。
